USE [master]
GO

/****** Object:  Database [Tomasos]    Script Date: 4/22/2021 3:19:37 PM ******/
CREATE DATABASE [Tomasos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tomasos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Tomasos.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Tomasos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Tomasos_log.ldf' , SIZE = 5184KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tomasos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tomasos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tomasos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tomasos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tomasos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tomasos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tomasos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Tomasos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tomasos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tomasos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tomasos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tomasos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tomasos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tomasos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tomasos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tomasos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Tomasos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tomasos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tomasos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tomasos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tomasos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tomasos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tomasos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tomasos] SET RECOVERY FULL 
GO

ALTER DATABASE [Tomasos] SET  MULTI_USER 
GO

ALTER DATABASE [Tomasos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tomasos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tomasos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tomasos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Tomasos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Tomasos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Tomasos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Tomasos] SET  READ_WRITE 
GO

